### ISSUE TITLE
Tug Up Always recreating

### ISSUE THREAD

**Issue by tcoats** [metocean/tugboat#7]
```
[root@steven-pc]/home/steven/test# more steven.yml
crate1:
  volumes: 
    - /datastore:/datastore
  image: crate
  environment:
    - CLUSTER_NAME=steven
    - NODE_NAME=Node1
  command: /run.sh

crate2:
  volumes: 
    - /datastore:/datastore
  image: crate
  environment:
    - CLUSTER_NAME=steven
    - NODE_NAME=Node2
  command: /run.sh

crate3:
  volumes: 
    - /datastore:/datastore
  image: crate
  environment:
    - CLUSTER_NAME=steven
    - NODE_NAME=Node3
  command: /run.sh
```
